version = 1

test_patterns = ["test/**"]

exclude_patterns = ["tools/**"]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["nodejs"]

[[transformers]]
name = "clang-format"